API-KEY="simon-is-the-bestAPAPSPSPAP"
AWS_SECRET_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
apikey = "AKIAEXAMPLEKEY12345678"
API-KEY="simon-is-the-bestAPAPSPSPAP"
AWS_SECRET_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
apikey = "AKIAEXAMPLEKEY12345678"
AWS_SECRET_ACCESS_KEY2=AKIAIOSFODNN7EXAMPLE
apikey2 = "AKIAEXAMPLEKEY12345678"
