name: Gitleaks Full Repo Scan

on:
  pull_request:
    branches: [main]

jobs:
  gitleaks-scan:
    name: Gitleaks Full Commit History Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full commit history

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_RUN_ARGS: detect --source=. --verbose --report-format sarif --exit-code 1

