name: Gitleaks Secret Scan

on:
  pull_request:
    branches: [main]

jobs:
  gitleaks-scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fix for ambiguous commit errors

      - name: Run Gitleaks on Git history
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --report-format=sarif --report-path=gitleaks-history.sarif --exit-code 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Gitleaks on working directory (no-git)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --no-git --redact --report-format=sarif --report-path=gitleaks-current.sarif --exit-code 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

