name: Gitleaks Secret Scan

on:
  pull_request:
    branches: [main]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full git history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --redact --exit-code 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
