name: Gitleaks Secret Scan

on:
  pull_request:
    branches: [main]

jobs:
  gitleaks-scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full commit history is available

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --exit-code 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

